### ISSUE TITLE
The XML element Configuration does not allow attributes.

### ISSUE THREAD

**Issue by MichaelGrafnetter** [felixfbecker/PowerShellXSD#11]
Hi @felixfbecker , great job! I was about to create an XML schema for ps1xml by hand when I discovered your repo.
Unfortunately, PowerShell fails to import format files that start like this: 
```xml
<?xml version="1.0" encoding="utf-8" ?>
 <Configuration xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/felixfbecker/PowerShellXSD/master/Format.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
```

I am getting the following error for all format files:

> Import-Module : Errors occurred while loading the format data file: ...
> Error at XPath  in file ... : The XML element Configuration does not allow attributes.

Have you found a way to overcome this problem or do I have to remove the schema reference each time I am done with editing a format file?

**Comment by felixfbecker** [comment]
Yup, you can associate a schema with files through editor settings. Check out the guide I contributed to the VS Code docs: https://code.visualstudio.com/docs/languages/powershell#_typesps1xml-and-formatps1xml-files

**Comment by MichaelGrafnetter** [comment]
Thx. I mostly use full VS because of binary PS modules. I have figured out that adding

```xml
  <Association extension="ps1xml" schema="https://raw.githubusercontent.com/PowerShell/PowerShell/master/src/Schemas/Format.xsd" enableValidation="true"/>
  <Association extension="ps1xml" schema="https://raw.githubusercontent.com/PowerShell/PowerShell/master/src/Schemas/Types.xsd" enableValidation="true"/>
```

to the `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Xml\Schemas\catalog.xml` file does the job. However, I am still looking for a way of adding the schema association to version control.

**Comment by felixfbecker** [comment]
Yeah, I don't know a solution that works with version control for VS (for VS Code you could check in the settings in a `.vscode/settings.json`).

I mentioned this problem in this issue here: https://github.com/PowerShell/PowerShell/issues/7749#issue-358607847

@SteveL-MSFT's last comment on it was

> I'll have a PR to allow attributes on the <Configuration> node, however.

But I think it's still not possible (probably fell trough the cracks)

**Comment by felixfbecker** [comment]
Closing since there's nothing I can do in this repo, let's move discussion to that issue
